main: lewan24.profileStaticItem.main
name: ProfileStaticItem

version: '1.5'
api-version: '1.21'

authors: [ Lewan24 ]
description: Simple plugin to handle static item in inventory that opens selected command while clicked
website: https://github.com/Lewan24


commands:
  staticItem:
    usage: "/<command> [reload]"